/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiceAutoRouteImport } from './routes/service-auto'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ScoliRouteImport } from './routes/scoli'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RestaurantRouteImport } from './routes/restaurant'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OfertaRouteImport } from './routes/oferta'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as ImobiliareRouteImport } from './routes/imobiliare'
import { Route as HelpCenterRouteImport } from './routes/help-center'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FitnessRouteImport } from './routes/fitness'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as DentistRouteImport } from './routes/dentist'
import { Route as CursuriRouteImport } from './routes/cursuri'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConstructiiRouteImport } from './routes/constructii'
import { Route as CliniciRouteImport } from './routes/clinici'
import { Route as BeautyRouteImport } from './routes/beauty'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as BSlugRouteImport } from './routes/b.$slug'
import { Route as AuthWelcomeRouteImport } from './routes/auth.welcome'
import { Route as AuthVerifiedRouteImport } from './routes/auth.verified'
import { Route as AuthConfirmEmailRouteImport } from './routes/auth.confirm-email'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProgramariRouteImport } from './routes/_authenticated/programari'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMetaStatusRouteImport } from './routes/_authenticated/meta-status'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCreateRouteImport } from './routes/_authenticated/create'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedQaTrialRouteImport } from './routes/_authenticated/qa.trial'
import { Route as AuthenticatedCampaignsIdRouteImport } from './routes/_authenticated/campaigns.$id'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp.webhook'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicMetaWebhookRouteImport } from './routes/api/public/meta.webhook'
import { Route as ApiPublicHooksWaKeepaliveRouteImport } from './routes/api/public/hooks/wa-keepalive'
import { Route as ApiPublicHooksSyncMetaLeadsRouteImport } from './routes/api/public/hooks/sync-meta-leads'
import { Route as ApiPublicHooksRefreshInsightsRouteImport } from './routes/api/public/hooks/refresh-insights'
import { Route as ApiPublicHooksPeriodicUpdateRouteImport } from './routes/api/public/hooks/periodic-update'
import { Route as ApiPublicHooksNewSignupRouteImport } from './routes/api/public/hooks/new-signup'
import { Route as ApiPublicHooksFreePlanExpiryRouteImport } from './routes/api/public/hooks/free-plan-expiry'
import { Route as ApiPublicHooksDailyReportRouteImport } from './routes/api/public/hooks/daily-report'
import { Route as ApiPublicHooksAnomalyScanRouteImport } from './routes/api/public/hooks/anomaly-scan'
import { Route as ApiPublicHooksActivationRemindersRouteImport } from './routes/api/public/hooks/activation-reminders'
import { Route as ApiMetaAuthCallbackRouteImport } from './routes/api/meta.auth.callback'
import { Route as AuthenticatedAdminUsersIdRouteImport } from './routes/_authenticated/admin.users.$id'
import { Route as AuthenticatedAdminTicketsIdRouteImport } from './routes/_authenticated/admin.tickets.$id'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAutoRoute = ServiceAutoRouteImport.update({
  id: '/service-auto',
  path: '/service-auto',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoliRoute = ScoliRouteImport.update({
  id: '/scoli',
  path: '/scoli',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRoute = RestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaRoute = OfertaRouteImport.update({
  id: '/oferta',
  path: '/oferta',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ImobiliareRoute = ImobiliareRouteImport.update({
  id: '/imobiliare',
  path: '/imobiliare',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCenterRoute = HelpCenterRouteImport.update({
  id: '/help-center',
  path: '/help-center',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FitnessRoute = FitnessRouteImport.update({
  id: '/fitness',
  path: '/fitness',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const DentistRoute = DentistRouteImport.update({
  id: '/dentist',
  path: '/dentist',
  getParentRoute: () => rootRouteImport,
} as any)
const CursuriRoute = CursuriRouteImport.update({
  id: '/cursuri',
  path: '/cursuri',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructiiRoute = ConstructiiRouteImport.update({
  id: '/constructii',
  path: '/constructii',
  getParentRoute: () => rootRouteImport,
} as any)
const CliniciRoute = CliniciRouteImport.update({
  id: '/clinici',
  path: '/clinici',
  getParentRoute: () => rootRouteImport,
} as any)
const BeautyRoute = BeautyRouteImport.update({
  id: '/beauty',
  path: '/beauty',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWelcomeRoute = AuthWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifiedRoute = AuthVerifiedRouteImport.update({
  id: '/verified',
  path: '/verified',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConfirmEmailRoute = AuthConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgramariRoute = AuthenticatedProgramariRouteImport.update({
  id: '/programari',
  path: '/programari',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetaStatusRoute = AuthenticatedMetaStatusRouteImport.update({
  id: '/meta-status',
  path: '/meta-status',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateRoute = AuthenticatedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQaTrialRoute = AuthenticatedQaTrialRouteImport.update({
  id: '/qa/trial',
  path: '/qa/trial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignsIdRoute =
  AuthenticatedCampaignsIdRouteImport.update({
    id: '/campaigns/$id',
    path: '/campaigns/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMetaWebhookRoute = ApiPublicMetaWebhookRouteImport.update({
  id: '/api/public/meta/webhook',
  path: '/api/public/meta/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksWaKeepaliveRoute =
  ApiPublicHooksWaKeepaliveRouteImport.update({
    id: '/api/public/hooks/wa-keepalive',
    path: '/api/public/hooks/wa-keepalive',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncMetaLeadsRoute =
  ApiPublicHooksSyncMetaLeadsRouteImport.update({
    id: '/api/public/hooks/sync-meta-leads',
    path: '/api/public/hooks/sync-meta-leads',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRefreshInsightsRoute =
  ApiPublicHooksRefreshInsightsRouteImport.update({
    id: '/api/public/hooks/refresh-insights',
    path: '/api/public/hooks/refresh-insights',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPeriodicUpdateRoute =
  ApiPublicHooksPeriodicUpdateRouteImport.update({
    id: '/api/public/hooks/periodic-update',
    path: '/api/public/hooks/periodic-update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNewSignupRoute = ApiPublicHooksNewSignupRouteImport.update({
  id: '/api/public/hooks/new-signup',
  path: '/api/public/hooks/new-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksFreePlanExpiryRoute =
  ApiPublicHooksFreePlanExpiryRouteImport.update({
    id: '/api/public/hooks/free-plan-expiry',
    path: '/api/public/hooks/free-plan-expiry',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyReportRoute =
  ApiPublicHooksDailyReportRouteImport.update({
    id: '/api/public/hooks/daily-report',
    path: '/api/public/hooks/daily-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAnomalyScanRoute =
  ApiPublicHooksAnomalyScanRouteImport.update({
    id: '/api/public/hooks/anomaly-scan',
    path: '/api/public/hooks/anomaly-scan',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksActivationRemindersRoute =
  ApiPublicHooksActivationRemindersRouteImport.update({
    id: '/api/public/hooks/activation-reminders',
    path: '/api/public/hooks/activation-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMetaAuthCallbackRoute = ApiMetaAuthCallbackRouteImport.update({
  id: '/api/meta/auth/callback',
  path: '/api/meta/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUsersIdRoute =
  AuthenticatedAdminUsersIdRouteImport.update({
    id: '/users/$id',
    path: '/users/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTicketsIdRoute =
  AuthenticatedAdminTicketsIdRouteImport.update({
    id: '/tickets/$id',
    path: '/tickets/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/beauty': typeof BeautyRoute
  '/clinici': typeof CliniciRoute
  '/constructii': typeof ConstructiiRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/cursuri': typeof CursuriRoute
  '/dentist': typeof DentistRoute
  '/documentation': typeof DocumentationRoute
  '/features': typeof FeaturesRoute
  '/fitness': typeof FitnessRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gdpr': typeof GdprRoute
  '/help': typeof HelpRoute
  '/help-center': typeof HelpCenterRoute
  '/imobiliare': typeof ImobiliareRoute
  '/integrations': typeof IntegrationsRoute
  '/oferta': typeof OfertaRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurant': typeof RestaurantRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/scoli': typeof ScoliRoute
  '/security': typeof SecurityRoute
  '/service-auto': typeof ServiceAutoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/bookings': typeof AuthenticatedBookingsRoute
  '/create': typeof AuthenticatedCreateRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/meta-status': typeof AuthenticatedMetaStatusRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/programari': typeof AuthenticatedProgramariRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/auth/welcome': typeof AuthWelcomeRoute
  '/b/$slug': typeof BSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/qa/trial': typeof AuthenticatedQaTrialRoute
  '/admin/tickets/$id': typeof AuthenticatedAdminTicketsIdRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/api/meta/auth/callback': typeof ApiMetaAuthCallbackRoute
  '/api/public/hooks/activation-reminders': typeof ApiPublicHooksActivationRemindersRoute
  '/api/public/hooks/anomaly-scan': typeof ApiPublicHooksAnomalyScanRoute
  '/api/public/hooks/daily-report': typeof ApiPublicHooksDailyReportRoute
  '/api/public/hooks/free-plan-expiry': typeof ApiPublicHooksFreePlanExpiryRoute
  '/api/public/hooks/new-signup': typeof ApiPublicHooksNewSignupRoute
  '/api/public/hooks/periodic-update': typeof ApiPublicHooksPeriodicUpdateRoute
  '/api/public/hooks/refresh-insights': typeof ApiPublicHooksRefreshInsightsRoute
  '/api/public/hooks/sync-meta-leads': typeof ApiPublicHooksSyncMetaLeadsRoute
  '/api/public/hooks/wa-keepalive': typeof ApiPublicHooksWaKeepaliveRoute
  '/api/public/meta/webhook': typeof ApiPublicMetaWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/beauty': typeof BeautyRoute
  '/clinici': typeof CliniciRoute
  '/constructii': typeof ConstructiiRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/cursuri': typeof CursuriRoute
  '/dentist': typeof DentistRoute
  '/documentation': typeof DocumentationRoute
  '/features': typeof FeaturesRoute
  '/fitness': typeof FitnessRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gdpr': typeof GdprRoute
  '/help': typeof HelpRoute
  '/help-center': typeof HelpCenterRoute
  '/imobiliare': typeof ImobiliareRoute
  '/integrations': typeof IntegrationsRoute
  '/oferta': typeof OfertaRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurant': typeof RestaurantRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/scoli': typeof ScoliRoute
  '/security': typeof SecurityRoute
  '/service-auto': typeof ServiceAutoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/bookings': typeof AuthenticatedBookingsRoute
  '/create': typeof AuthenticatedCreateRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/meta-status': typeof AuthenticatedMetaStatusRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/programari': typeof AuthenticatedProgramariRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/auth/welcome': typeof AuthWelcomeRoute
  '/b/$slug': typeof BSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/qa/trial': typeof AuthenticatedQaTrialRoute
  '/admin/tickets/$id': typeof AuthenticatedAdminTicketsIdRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/api/meta/auth/callback': typeof ApiMetaAuthCallbackRoute
  '/api/public/hooks/activation-reminders': typeof ApiPublicHooksActivationRemindersRoute
  '/api/public/hooks/anomaly-scan': typeof ApiPublicHooksAnomalyScanRoute
  '/api/public/hooks/daily-report': typeof ApiPublicHooksDailyReportRoute
  '/api/public/hooks/free-plan-expiry': typeof ApiPublicHooksFreePlanExpiryRoute
  '/api/public/hooks/new-signup': typeof ApiPublicHooksNewSignupRoute
  '/api/public/hooks/periodic-update': typeof ApiPublicHooksPeriodicUpdateRoute
  '/api/public/hooks/refresh-insights': typeof ApiPublicHooksRefreshInsightsRoute
  '/api/public/hooks/sync-meta-leads': typeof ApiPublicHooksSyncMetaLeadsRoute
  '/api/public/hooks/wa-keepalive': typeof ApiPublicHooksWaKeepaliveRoute
  '/api/public/meta/webhook': typeof ApiPublicMetaWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/beauty': typeof BeautyRoute
  '/clinici': typeof CliniciRoute
  '/constructii': typeof ConstructiiRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/cursuri': typeof CursuriRoute
  '/dentist': typeof DentistRoute
  '/documentation': typeof DocumentationRoute
  '/features': typeof FeaturesRoute
  '/fitness': typeof FitnessRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gdpr': typeof GdprRoute
  '/help': typeof HelpRoute
  '/help-center': typeof HelpCenterRoute
  '/imobiliare': typeof ImobiliareRoute
  '/integrations': typeof IntegrationsRoute
  '/oferta': typeof OfertaRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurant': typeof RestaurantRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/scoli': typeof ScoliRoute
  '/security': typeof SecurityRoute
  '/service-auto': typeof ServiceAutoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/create': typeof AuthenticatedCreateRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/meta-status': typeof AuthenticatedMetaStatusRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/programari': typeof AuthenticatedProgramariRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/verified': typeof AuthVerifiedRoute
  '/auth/welcome': typeof AuthWelcomeRoute
  '/b/$slug': typeof BSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/_authenticated/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/_authenticated/qa/trial': typeof AuthenticatedQaTrialRoute
  '/_authenticated/admin/tickets/$id': typeof AuthenticatedAdminTicketsIdRoute
  '/_authenticated/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/api/meta/auth/callback': typeof ApiMetaAuthCallbackRoute
  '/api/public/hooks/activation-reminders': typeof ApiPublicHooksActivationRemindersRoute
  '/api/public/hooks/anomaly-scan': typeof ApiPublicHooksAnomalyScanRoute
  '/api/public/hooks/daily-report': typeof ApiPublicHooksDailyReportRoute
  '/api/public/hooks/free-plan-expiry': typeof ApiPublicHooksFreePlanExpiryRoute
  '/api/public/hooks/new-signup': typeof ApiPublicHooksNewSignupRoute
  '/api/public/hooks/periodic-update': typeof ApiPublicHooksPeriodicUpdateRoute
  '/api/public/hooks/refresh-insights': typeof ApiPublicHooksRefreshInsightsRoute
  '/api/public/hooks/sync-meta-leads': typeof ApiPublicHooksSyncMetaLeadsRoute
  '/api/public/hooks/wa-keepalive': typeof ApiPublicHooksWaKeepaliveRoute
  '/api/public/meta/webhook': typeof ApiPublicMetaWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/beauty'
    | '/clinici'
    | '/constructii'
    | '/contact'
    | '/cookie-policy'
    | '/cursuri'
    | '/dentist'
    | '/documentation'
    | '/features'
    | '/fitness'
    | '/forgot-password'
    | '/gdpr'
    | '/help'
    | '/help-center'
    | '/imobiliare'
    | '/integrations'
    | '/oferta'
    | '/pricing'
    | '/privacy-policy'
    | '/refund-policy'
    | '/reset-password'
    | '/restaurant'
    | '/robots.txt'
    | '/scoli'
    | '/security'
    | '/service-auto'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/admin'
    | '/bookings'
    | '/create'
    | '/dashboard'
    | '/leads'
    | '/meta-status'
    | '/onboarding'
    | '/programari'
    | '/reports'
    | '/settings'
    | '/support'
    | '/whatsapp'
    | '/auth/callback'
    | '/auth/confirm-email'
    | '/auth/verified'
    | '/auth/welcome'
    | '/b/$slug'
    | '/checkout/return'
    | '/campaigns/$id'
    | '/qa/trial'
    | '/admin/tickets/$id'
    | '/admin/users/$id'
    | '/api/meta/auth/callback'
    | '/api/public/hooks/activation-reminders'
    | '/api/public/hooks/anomaly-scan'
    | '/api/public/hooks/daily-report'
    | '/api/public/hooks/free-plan-expiry'
    | '/api/public/hooks/new-signup'
    | '/api/public/hooks/periodic-update'
    | '/api/public/hooks/refresh-insights'
    | '/api/public/hooks/sync-meta-leads'
    | '/api/public/hooks/wa-keepalive'
    | '/api/public/meta/webhook'
    | '/api/public/payments/webhook'
    | '/api/public/whatsapp/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/beauty'
    | '/clinici'
    | '/constructii'
    | '/contact'
    | '/cookie-policy'
    | '/cursuri'
    | '/dentist'
    | '/documentation'
    | '/features'
    | '/fitness'
    | '/forgot-password'
    | '/gdpr'
    | '/help'
    | '/help-center'
    | '/imobiliare'
    | '/integrations'
    | '/oferta'
    | '/pricing'
    | '/privacy-policy'
    | '/refund-policy'
    | '/reset-password'
    | '/restaurant'
    | '/robots.txt'
    | '/scoli'
    | '/security'
    | '/service-auto'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/admin'
    | '/bookings'
    | '/create'
    | '/dashboard'
    | '/leads'
    | '/meta-status'
    | '/onboarding'
    | '/programari'
    | '/reports'
    | '/settings'
    | '/support'
    | '/whatsapp'
    | '/auth/callback'
    | '/auth/confirm-email'
    | '/auth/verified'
    | '/auth/welcome'
    | '/b/$slug'
    | '/checkout/return'
    | '/campaigns/$id'
    | '/qa/trial'
    | '/admin/tickets/$id'
    | '/admin/users/$id'
    | '/api/meta/auth/callback'
    | '/api/public/hooks/activation-reminders'
    | '/api/public/hooks/anomaly-scan'
    | '/api/public/hooks/daily-report'
    | '/api/public/hooks/free-plan-expiry'
    | '/api/public/hooks/new-signup'
    | '/api/public/hooks/periodic-update'
    | '/api/public/hooks/refresh-insights'
    | '/api/public/hooks/sync-meta-leads'
    | '/api/public/hooks/wa-keepalive'
    | '/api/public/meta/webhook'
    | '/api/public/payments/webhook'
    | '/api/public/whatsapp/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/beauty'
    | '/clinici'
    | '/constructii'
    | '/contact'
    | '/cookie-policy'
    | '/cursuri'
    | '/dentist'
    | '/documentation'
    | '/features'
    | '/fitness'
    | '/forgot-password'
    | '/gdpr'
    | '/help'
    | '/help-center'
    | '/imobiliare'
    | '/integrations'
    | '/oferta'
    | '/pricing'
    | '/privacy-policy'
    | '/refund-policy'
    | '/reset-password'
    | '/restaurant'
    | '/robots.txt'
    | '/scoli'
    | '/security'
    | '/service-auto'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/_authenticated/admin'
    | '/_authenticated/bookings'
    | '/_authenticated/create'
    | '/_authenticated/dashboard'
    | '/_authenticated/leads'
    | '/_authenticated/meta-status'
    | '/_authenticated/onboarding'
    | '/_authenticated/programari'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/support'
    | '/_authenticated/whatsapp'
    | '/auth/callback'
    | '/auth/confirm-email'
    | '/auth/verified'
    | '/auth/welcome'
    | '/b/$slug'
    | '/checkout/return'
    | '/_authenticated/campaigns/$id'
    | '/_authenticated/qa/trial'
    | '/_authenticated/admin/tickets/$id'
    | '/_authenticated/admin/users/$id'
    | '/api/meta/auth/callback'
    | '/api/public/hooks/activation-reminders'
    | '/api/public/hooks/anomaly-scan'
    | '/api/public/hooks/daily-report'
    | '/api/public/hooks/free-plan-expiry'
    | '/api/public/hooks/new-signup'
    | '/api/public/hooks/periodic-update'
    | '/api/public/hooks/refresh-insights'
    | '/api/public/hooks/sync-meta-leads'
    | '/api/public/hooks/wa-keepalive'
    | '/api/public/meta/webhook'
    | '/api/public/payments/webhook'
    | '/api/public/whatsapp/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  BeautyRoute: typeof BeautyRoute
  CliniciRoute: typeof CliniciRoute
  ConstructiiRoute: typeof ConstructiiRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  CursuriRoute: typeof CursuriRoute
  DentistRoute: typeof DentistRoute
  DocumentationRoute: typeof DocumentationRoute
  FeaturesRoute: typeof FeaturesRoute
  FitnessRoute: typeof FitnessRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GdprRoute: typeof GdprRoute
  HelpRoute: typeof HelpRoute
  HelpCenterRoute: typeof HelpCenterRoute
  ImobiliareRoute: typeof ImobiliareRoute
  IntegrationsRoute: typeof IntegrationsRoute
  OfertaRoute: typeof OfertaRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RestaurantRoute: typeof RestaurantRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ScoliRoute: typeof ScoliRoute
  SecurityRoute: typeof SecurityRoute
  ServiceAutoRoute: typeof ServiceAutoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  BSlugRoute: typeof BSlugRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiMetaAuthCallbackRoute: typeof ApiMetaAuthCallbackRoute
  ApiPublicHooksActivationRemindersRoute: typeof ApiPublicHooksActivationRemindersRoute
  ApiPublicHooksAnomalyScanRoute: typeof ApiPublicHooksAnomalyScanRoute
  ApiPublicHooksDailyReportRoute: typeof ApiPublicHooksDailyReportRoute
  ApiPublicHooksFreePlanExpiryRoute: typeof ApiPublicHooksFreePlanExpiryRoute
  ApiPublicHooksNewSignupRoute: typeof ApiPublicHooksNewSignupRoute
  ApiPublicHooksPeriodicUpdateRoute: typeof ApiPublicHooksPeriodicUpdateRoute
  ApiPublicHooksRefreshInsightsRoute: typeof ApiPublicHooksRefreshInsightsRoute
  ApiPublicHooksSyncMetaLeadsRoute: typeof ApiPublicHooksSyncMetaLeadsRoute
  ApiPublicHooksWaKeepaliveRoute: typeof ApiPublicHooksWaKeepaliveRoute
  ApiPublicMetaWebhookRoute: typeof ApiPublicMetaWebhookRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-auto': {
      id: '/service-auto'
      path: '/service-auto'
      fullPath: '/service-auto'
      preLoaderRoute: typeof ServiceAutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoli': {
      id: '/scoli'
      path: '/scoli'
      fullPath: '/scoli'
      preLoaderRoute: typeof ScoliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant': {
      id: '/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta': {
      id: '/oferta'
      path: '/oferta'
      fullPath: '/oferta'
      preLoaderRoute: typeof OfertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imobiliare': {
      id: '/imobiliare'
      path: '/imobiliare'
      fullPath: '/imobiliare'
      preLoaderRoute: typeof ImobiliareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-center': {
      id: '/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof HelpCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fitness': {
      id: '/fitness'
      path: '/fitness'
      fullPath: '/fitness'
      preLoaderRoute: typeof FitnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dentist': {
      id: '/dentist'
      path: '/dentist'
      fullPath: '/dentist'
      preLoaderRoute: typeof DentistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursuri': {
      id: '/cursuri'
      path: '/cursuri'
      fullPath: '/cursuri'
      preLoaderRoute: typeof CursuriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constructii': {
      id: '/constructii'
      path: '/constructii'
      fullPath: '/constructii'
      preLoaderRoute: typeof ConstructiiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinici': {
      id: '/clinici'
      path: '/clinici'
      fullPath: '/clinici'
      preLoaderRoute: typeof CliniciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beauty': {
      id: '/beauty'
      path: '/beauty'
      fullPath: '/beauty'
      preLoaderRoute: typeof BeautyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/welcome': {
      id: '/auth/welcome'
      path: '/welcome'
      fullPath: '/auth/welcome'
      preLoaderRoute: typeof AuthWelcomeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/verified': {
      id: '/auth/verified'
      path: '/verified'
      fullPath: '/auth/verified'
      preLoaderRoute: typeof AuthVerifiedRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/confirm-email': {
      id: '/auth/confirm-email'
      path: '/confirm-email'
      fullPath: '/auth/confirm-email'
      preLoaderRoute: typeof AuthConfirmEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programari': {
      id: '/_authenticated/programari'
      path: '/programari'
      fullPath: '/programari'
      preLoaderRoute: typeof AuthenticatedProgramariRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meta-status': {
      id: '/_authenticated/meta-status'
      path: '/meta-status'
      fullPath: '/meta-status'
      preLoaderRoute: typeof AuthenticatedMetaStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qa/trial': {
      id: '/_authenticated/qa/trial'
      path: '/qa/trial'
      fullPath: '/qa/trial'
      preLoaderRoute: typeof AuthenticatedQaTrialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/$id': {
      id: '/_authenticated/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AuthenticatedCampaignsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta/webhook': {
      id: '/api/public/meta/webhook'
      path: '/api/public/meta/webhook'
      fullPath: '/api/public/meta/webhook'
      preLoaderRoute: typeof ApiPublicMetaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/wa-keepalive': {
      id: '/api/public/hooks/wa-keepalive'
      path: '/api/public/hooks/wa-keepalive'
      fullPath: '/api/public/hooks/wa-keepalive'
      preLoaderRoute: typeof ApiPublicHooksWaKeepaliveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-meta-leads': {
      id: '/api/public/hooks/sync-meta-leads'
      path: '/api/public/hooks/sync-meta-leads'
      fullPath: '/api/public/hooks/sync-meta-leads'
      preLoaderRoute: typeof ApiPublicHooksSyncMetaLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-insights': {
      id: '/api/public/hooks/refresh-insights'
      path: '/api/public/hooks/refresh-insights'
      fullPath: '/api/public/hooks/refresh-insights'
      preLoaderRoute: typeof ApiPublicHooksRefreshInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/periodic-update': {
      id: '/api/public/hooks/periodic-update'
      path: '/api/public/hooks/periodic-update'
      fullPath: '/api/public/hooks/periodic-update'
      preLoaderRoute: typeof ApiPublicHooksPeriodicUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/new-signup': {
      id: '/api/public/hooks/new-signup'
      path: '/api/public/hooks/new-signup'
      fullPath: '/api/public/hooks/new-signup'
      preLoaderRoute: typeof ApiPublicHooksNewSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/free-plan-expiry': {
      id: '/api/public/hooks/free-plan-expiry'
      path: '/api/public/hooks/free-plan-expiry'
      fullPath: '/api/public/hooks/free-plan-expiry'
      preLoaderRoute: typeof ApiPublicHooksFreePlanExpiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-report': {
      id: '/api/public/hooks/daily-report'
      path: '/api/public/hooks/daily-report'
      fullPath: '/api/public/hooks/daily-report'
      preLoaderRoute: typeof ApiPublicHooksDailyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/anomaly-scan': {
      id: '/api/public/hooks/anomaly-scan'
      path: '/api/public/hooks/anomaly-scan'
      fullPath: '/api/public/hooks/anomaly-scan'
      preLoaderRoute: typeof ApiPublicHooksAnomalyScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/activation-reminders': {
      id: '/api/public/hooks/activation-reminders'
      path: '/api/public/hooks/activation-reminders'
      fullPath: '/api/public/hooks/activation-reminders'
      preLoaderRoute: typeof ApiPublicHooksActivationRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta/auth/callback': {
      id: '/api/meta/auth/callback'
      path: '/api/meta/auth/callback'
      fullPath: '/api/meta/auth/callback'
      preLoaderRoute: typeof ApiMetaAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/users/$id': {
      id: '/_authenticated/admin/users/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedAdminUsersIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tickets/$id': {
      id: '/_authenticated/admin/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/admin/tickets/$id'
      preLoaderRoute: typeof AuthenticatedAdminTicketsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminTicketsIdRoute: typeof AuthenticatedAdminTicketsIdRoute
  AuthenticatedAdminUsersIdRoute: typeof AuthenticatedAdminUsersIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminTicketsIdRoute: AuthenticatedAdminTicketsIdRoute,
  AuthenticatedAdminUsersIdRoute: AuthenticatedAdminUsersIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedCreateRoute: typeof AuthenticatedCreateRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedMetaStatusRoute: typeof AuthenticatedMetaStatusRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProgramariRoute: typeof AuthenticatedProgramariRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
  AuthenticatedCampaignsIdRoute: typeof AuthenticatedCampaignsIdRoute
  AuthenticatedQaTrialRoute: typeof AuthenticatedQaTrialRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedCreateRoute: AuthenticatedCreateRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedMetaStatusRoute: AuthenticatedMetaStatusRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProgramariRoute: AuthenticatedProgramariRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
  AuthenticatedCampaignsIdRoute: AuthenticatedCampaignsIdRoute,
  AuthenticatedQaTrialRoute: AuthenticatedQaTrialRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthConfirmEmailRoute: typeof AuthConfirmEmailRoute
  AuthVerifiedRoute: typeof AuthVerifiedRoute
  AuthWelcomeRoute: typeof AuthWelcomeRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthConfirmEmailRoute: AuthConfirmEmailRoute,
  AuthVerifiedRoute: AuthVerifiedRoute,
  AuthWelcomeRoute: AuthWelcomeRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  BeautyRoute: BeautyRoute,
  CliniciRoute: CliniciRoute,
  ConstructiiRoute: ConstructiiRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  CursuriRoute: CursuriRoute,
  DentistRoute: DentistRoute,
  DocumentationRoute: DocumentationRoute,
  FeaturesRoute: FeaturesRoute,
  FitnessRoute: FitnessRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GdprRoute: GdprRoute,
  HelpRoute: HelpRoute,
  HelpCenterRoute: HelpCenterRoute,
  ImobiliareRoute: ImobiliareRoute,
  IntegrationsRoute: IntegrationsRoute,
  OfertaRoute: OfertaRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RestaurantRoute: RestaurantRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ScoliRoute: ScoliRoute,
  SecurityRoute: SecurityRoute,
  ServiceAutoRoute: ServiceAutoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  BSlugRoute: BSlugRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiMetaAuthCallbackRoute: ApiMetaAuthCallbackRoute,
  ApiPublicHooksActivationRemindersRoute:
    ApiPublicHooksActivationRemindersRoute,
  ApiPublicHooksAnomalyScanRoute: ApiPublicHooksAnomalyScanRoute,
  ApiPublicHooksDailyReportRoute: ApiPublicHooksDailyReportRoute,
  ApiPublicHooksFreePlanExpiryRoute: ApiPublicHooksFreePlanExpiryRoute,
  ApiPublicHooksNewSignupRoute: ApiPublicHooksNewSignupRoute,
  ApiPublicHooksPeriodicUpdateRoute: ApiPublicHooksPeriodicUpdateRoute,
  ApiPublicHooksRefreshInsightsRoute: ApiPublicHooksRefreshInsightsRoute,
  ApiPublicHooksSyncMetaLeadsRoute: ApiPublicHooksSyncMetaLeadsRoute,
  ApiPublicHooksWaKeepaliveRoute: ApiPublicHooksWaKeepaliveRoute,
  ApiPublicMetaWebhookRoute: ApiPublicMetaWebhookRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
