/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as HelpCenterRouteImport } from './routes/help-center'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedMetaStatusRouteImport } from './routes/_authenticated/meta-status'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCreateRouteImport } from './routes/_authenticated/create'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicAdminBootstrapRouteImport } from './routes/api/public/admin-bootstrap'
import { Route as AuthenticatedCampaignsIdRouteImport } from './routes/_authenticated/campaigns.$id'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp.webhook'
import { Route as ApiPublicMetaWebhookRouteImport } from './routes/api/public/meta.webhook'
import { Route as ApiPublicHooksRefreshInsightsRouteImport } from './routes/api/public/hooks/refresh-insights'
import { Route as ApiPublicHooksPeriodicUpdateRouteImport } from './routes/api/public/hooks/periodic-update'
import { Route as ApiPublicHooksDailyReportRouteImport } from './routes/api/public/hooks/daily-report'
import { Route as ApiPublicHooksAnomalyScanRouteImport } from './routes/api/public/hooks/anomaly-scan'
import { Route as ApiMetaAuthStartRouteImport } from './routes/api/meta.auth.start'
import { Route as ApiMetaAuthCallbackRouteImport } from './routes/api/meta.auth.callback'
import { Route as AuthenticatedAdminUsersIdRouteImport } from './routes/_authenticated/admin.users.$id'
import { Route as AuthenticatedAdminTicketsIdRouteImport } from './routes/_authenticated/admin.tickets.$id'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCenterRoute = HelpCenterRouteImport.update({
  id: '/help-center',
  path: '/help-center',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetaStatusRoute = AuthenticatedMetaStatusRouteImport.update({
  id: '/meta-status',
  path: '/meta-status',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateRoute = AuthenticatedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicAdminBootstrapRoute = ApiPublicAdminBootstrapRouteImport.update({
  id: '/api/public/admin-bootstrap',
  path: '/api/public/admin-bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCampaignsIdRoute =
  AuthenticatedCampaignsIdRouteImport.update({
    id: '/campaigns/$id',
    path: '/campaigns/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMetaWebhookRoute = ApiPublicMetaWebhookRouteImport.update({
  id: '/api/public/meta/webhook',
  path: '/api/public/meta/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRefreshInsightsRoute =
  ApiPublicHooksRefreshInsightsRouteImport.update({
    id: '/api/public/hooks/refresh-insights',
    path: '/api/public/hooks/refresh-insights',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPeriodicUpdateRoute =
  ApiPublicHooksPeriodicUpdateRouteImport.update({
    id: '/api/public/hooks/periodic-update',
    path: '/api/public/hooks/periodic-update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyReportRoute =
  ApiPublicHooksDailyReportRouteImport.update({
    id: '/api/public/hooks/daily-report',
    path: '/api/public/hooks/daily-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAnomalyScanRoute =
  ApiPublicHooksAnomalyScanRouteImport.update({
    id: '/api/public/hooks/anomaly-scan',
    path: '/api/public/hooks/anomaly-scan',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMetaAuthStartRoute = ApiMetaAuthStartRouteImport.update({
  id: '/api/meta/auth/start',
  path: '/api/meta/auth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaAuthCallbackRoute = ApiMetaAuthCallbackRouteImport.update({
  id: '/api/meta/auth/callback',
  path: '/api/meta/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUsersIdRoute =
  AuthenticatedAdminUsersIdRouteImport.update({
    id: '/users/$id',
    path: '/users/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTicketsIdRoute =
  AuthenticatedAdminTicketsIdRouteImport.update({
    id: '/tickets/$id',
    path: '/tickets/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/documentation': typeof DocumentationRoute
  '/features': typeof FeaturesRoute
  '/gdpr': typeof GdprRoute
  '/help': typeof HelpRoute
  '/help-center': typeof HelpCenterRoute
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/security': typeof SecurityRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/create': typeof AuthenticatedCreateRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/meta-status': typeof AuthenticatedMetaStatusRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/api/public/admin-bootstrap': typeof ApiPublicAdminBootstrapRoute
  '/admin/tickets/$id': typeof AuthenticatedAdminTicketsIdRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/api/meta/auth/callback': typeof ApiMetaAuthCallbackRoute
  '/api/meta/auth/start': typeof ApiMetaAuthStartRoute
  '/api/public/hooks/anomaly-scan': typeof ApiPublicHooksAnomalyScanRoute
  '/api/public/hooks/daily-report': typeof ApiPublicHooksDailyReportRoute
  '/api/public/hooks/periodic-update': typeof ApiPublicHooksPeriodicUpdateRoute
  '/api/public/hooks/refresh-insights': typeof ApiPublicHooksRefreshInsightsRoute
  '/api/public/meta/webhook': typeof ApiPublicMetaWebhookRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/documentation': typeof DocumentationRoute
  '/features': typeof FeaturesRoute
  '/gdpr': typeof GdprRoute
  '/help': typeof HelpRoute
  '/help-center': typeof HelpCenterRoute
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/security': typeof SecurityRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/create': typeof AuthenticatedCreateRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/meta-status': typeof AuthenticatedMetaStatusRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/api/public/admin-bootstrap': typeof ApiPublicAdminBootstrapRoute
  '/admin/tickets/$id': typeof AuthenticatedAdminTicketsIdRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/api/meta/auth/callback': typeof ApiMetaAuthCallbackRoute
  '/api/meta/auth/start': typeof ApiMetaAuthStartRoute
  '/api/public/hooks/anomaly-scan': typeof ApiPublicHooksAnomalyScanRoute
  '/api/public/hooks/daily-report': typeof ApiPublicHooksDailyReportRoute
  '/api/public/hooks/periodic-update': typeof ApiPublicHooksPeriodicUpdateRoute
  '/api/public/hooks/refresh-insights': typeof ApiPublicHooksRefreshInsightsRoute
  '/api/public/meta/webhook': typeof ApiPublicMetaWebhookRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/documentation': typeof DocumentationRoute
  '/features': typeof FeaturesRoute
  '/gdpr': typeof GdprRoute
  '/help': typeof HelpRoute
  '/help-center': typeof HelpCenterRoute
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/security': typeof SecurityRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/create': typeof AuthenticatedCreateRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/meta-status': typeof AuthenticatedMetaStatusRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/_authenticated/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/api/public/admin-bootstrap': typeof ApiPublicAdminBootstrapRoute
  '/_authenticated/admin/tickets/$id': typeof AuthenticatedAdminTicketsIdRoute
  '/_authenticated/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/api/meta/auth/callback': typeof ApiMetaAuthCallbackRoute
  '/api/meta/auth/start': typeof ApiMetaAuthStartRoute
  '/api/public/hooks/anomaly-scan': typeof ApiPublicHooksAnomalyScanRoute
  '/api/public/hooks/daily-report': typeof ApiPublicHooksDailyReportRoute
  '/api/public/hooks/periodic-update': typeof ApiPublicHooksPeriodicUpdateRoute
  '/api/public/hooks/refresh-insights': typeof ApiPublicHooksRefreshInsightsRoute
  '/api/public/meta/webhook': typeof ApiPublicMetaWebhookRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/cookie-policy'
    | '/documentation'
    | '/features'
    | '/gdpr'
    | '/help'
    | '/help-center'
    | '/integrations'
    | '/pricing'
    | '/privacy-policy'
    | '/security'
    | '/terms-of-service'
    | '/admin'
    | '/create'
    | '/dashboard'
    | '/leads'
    | '/meta-status'
    | '/reports'
    | '/settings'
    | '/support'
    | '/whatsapp'
    | '/campaigns/$id'
    | '/api/public/admin-bootstrap'
    | '/admin/tickets/$id'
    | '/admin/users/$id'
    | '/api/meta/auth/callback'
    | '/api/meta/auth/start'
    | '/api/public/hooks/anomaly-scan'
    | '/api/public/hooks/daily-report'
    | '/api/public/hooks/periodic-update'
    | '/api/public/hooks/refresh-insights'
    | '/api/public/meta/webhook'
    | '/api/public/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/cookie-policy'
    | '/documentation'
    | '/features'
    | '/gdpr'
    | '/help'
    | '/help-center'
    | '/integrations'
    | '/pricing'
    | '/privacy-policy'
    | '/security'
    | '/terms-of-service'
    | '/admin'
    | '/create'
    | '/dashboard'
    | '/leads'
    | '/meta-status'
    | '/reports'
    | '/settings'
    | '/support'
    | '/whatsapp'
    | '/campaigns/$id'
    | '/api/public/admin-bootstrap'
    | '/admin/tickets/$id'
    | '/admin/users/$id'
    | '/api/meta/auth/callback'
    | '/api/meta/auth/start'
    | '/api/public/hooks/anomaly-scan'
    | '/api/public/hooks/daily-report'
    | '/api/public/hooks/periodic-update'
    | '/api/public/hooks/refresh-insights'
    | '/api/public/meta/webhook'
    | '/api/public/whatsapp/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/cookie-policy'
    | '/documentation'
    | '/features'
    | '/gdpr'
    | '/help'
    | '/help-center'
    | '/integrations'
    | '/pricing'
    | '/privacy-policy'
    | '/security'
    | '/terms-of-service'
    | '/_authenticated/admin'
    | '/_authenticated/create'
    | '/_authenticated/dashboard'
    | '/_authenticated/leads'
    | '/_authenticated/meta-status'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/support'
    | '/_authenticated/whatsapp'
    | '/_authenticated/campaigns/$id'
    | '/api/public/admin-bootstrap'
    | '/_authenticated/admin/tickets/$id'
    | '/_authenticated/admin/users/$id'
    | '/api/meta/auth/callback'
    | '/api/meta/auth/start'
    | '/api/public/hooks/anomaly-scan'
    | '/api/public/hooks/daily-report'
    | '/api/public/hooks/periodic-update'
    | '/api/public/hooks/refresh-insights'
    | '/api/public/meta/webhook'
    | '/api/public/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DocumentationRoute: typeof DocumentationRoute
  FeaturesRoute: typeof FeaturesRoute
  GdprRoute: typeof GdprRoute
  HelpRoute: typeof HelpRoute
  HelpCenterRoute: typeof HelpCenterRoute
  IntegrationsRoute: typeof IntegrationsRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SecurityRoute: typeof SecurityRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ApiPublicAdminBootstrapRoute: typeof ApiPublicAdminBootstrapRoute
  ApiMetaAuthCallbackRoute: typeof ApiMetaAuthCallbackRoute
  ApiMetaAuthStartRoute: typeof ApiMetaAuthStartRoute
  ApiPublicHooksAnomalyScanRoute: typeof ApiPublicHooksAnomalyScanRoute
  ApiPublicHooksDailyReportRoute: typeof ApiPublicHooksDailyReportRoute
  ApiPublicHooksPeriodicUpdateRoute: typeof ApiPublicHooksPeriodicUpdateRoute
  ApiPublicHooksRefreshInsightsRoute: typeof ApiPublicHooksRefreshInsightsRoute
  ApiPublicMetaWebhookRoute: typeof ApiPublicMetaWebhookRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-center': {
      id: '/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof HelpCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meta-status': {
      id: '/_authenticated/meta-status'
      path: '/meta-status'
      fullPath: '/meta-status'
      preLoaderRoute: typeof AuthenticatedMetaStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/admin-bootstrap': {
      id: '/api/public/admin-bootstrap'
      path: '/api/public/admin-bootstrap'
      fullPath: '/api/public/admin-bootstrap'
      preLoaderRoute: typeof ApiPublicAdminBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/campaigns/$id': {
      id: '/_authenticated/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AuthenticatedCampaignsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta/webhook': {
      id: '/api/public/meta/webhook'
      path: '/api/public/meta/webhook'
      fullPath: '/api/public/meta/webhook'
      preLoaderRoute: typeof ApiPublicMetaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-insights': {
      id: '/api/public/hooks/refresh-insights'
      path: '/api/public/hooks/refresh-insights'
      fullPath: '/api/public/hooks/refresh-insights'
      preLoaderRoute: typeof ApiPublicHooksRefreshInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/periodic-update': {
      id: '/api/public/hooks/periodic-update'
      path: '/api/public/hooks/periodic-update'
      fullPath: '/api/public/hooks/periodic-update'
      preLoaderRoute: typeof ApiPublicHooksPeriodicUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-report': {
      id: '/api/public/hooks/daily-report'
      path: '/api/public/hooks/daily-report'
      fullPath: '/api/public/hooks/daily-report'
      preLoaderRoute: typeof ApiPublicHooksDailyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/anomaly-scan': {
      id: '/api/public/hooks/anomaly-scan'
      path: '/api/public/hooks/anomaly-scan'
      fullPath: '/api/public/hooks/anomaly-scan'
      preLoaderRoute: typeof ApiPublicHooksAnomalyScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta/auth/start': {
      id: '/api/meta/auth/start'
      path: '/api/meta/auth/start'
      fullPath: '/api/meta/auth/start'
      preLoaderRoute: typeof ApiMetaAuthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta/auth/callback': {
      id: '/api/meta/auth/callback'
      path: '/api/meta/auth/callback'
      fullPath: '/api/meta/auth/callback'
      preLoaderRoute: typeof ApiMetaAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/users/$id': {
      id: '/_authenticated/admin/users/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedAdminUsersIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tickets/$id': {
      id: '/_authenticated/admin/tickets/$id'
      path: '/tickets/$id'
      fullPath: '/admin/tickets/$id'
      preLoaderRoute: typeof AuthenticatedAdminTicketsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminTicketsIdRoute: typeof AuthenticatedAdminTicketsIdRoute
  AuthenticatedAdminUsersIdRoute: typeof AuthenticatedAdminUsersIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminTicketsIdRoute: AuthenticatedAdminTicketsIdRoute,
  AuthenticatedAdminUsersIdRoute: AuthenticatedAdminUsersIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCreateRoute: typeof AuthenticatedCreateRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedMetaStatusRoute: typeof AuthenticatedMetaStatusRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
  AuthenticatedCampaignsIdRoute: typeof AuthenticatedCampaignsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCreateRoute: AuthenticatedCreateRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedMetaStatusRoute: AuthenticatedMetaStatusRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
  AuthenticatedCampaignsIdRoute: AuthenticatedCampaignsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DocumentationRoute: DocumentationRoute,
  FeaturesRoute: FeaturesRoute,
  GdprRoute: GdprRoute,
  HelpRoute: HelpRoute,
  HelpCenterRoute: HelpCenterRoute,
  IntegrationsRoute: IntegrationsRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SecurityRoute: SecurityRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ApiPublicAdminBootstrapRoute: ApiPublicAdminBootstrapRoute,
  ApiMetaAuthCallbackRoute: ApiMetaAuthCallbackRoute,
  ApiMetaAuthStartRoute: ApiMetaAuthStartRoute,
  ApiPublicHooksAnomalyScanRoute: ApiPublicHooksAnomalyScanRoute,
  ApiPublicHooksDailyReportRoute: ApiPublicHooksDailyReportRoute,
  ApiPublicHooksPeriodicUpdateRoute: ApiPublicHooksPeriodicUpdateRoute,
  ApiPublicHooksRefreshInsightsRoute: ApiPublicHooksRefreshInsightsRoute,
  ApiPublicMetaWebhookRoute: ApiPublicMetaWebhookRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
